---
apiVersion: v1
kind: Namespace
metadata:
  name: hpa-example
  labels:
    name: hpa-example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
  namespace: hpa-example
spec:
  selector:
    matchLabels:
      run: webserver
  replicas: 1
  template:
    metadata:
      labels:
        run: webserver
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: webserver
        volumeMounts:
        - mountPath: /tmp/
          name: tmp
          readOnly: false
        - mountPath: /.cache
          name: cache
          readOnly: false
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
            add:
             - NET_BIND_SERVICE
        image: manuelkasiske/docker-hpa-example
        ports:
          - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  namespace: hpa-example
  labels:
    run: webserver
spec:
  ports:
  - port: 80
    targetPort: 1025
  selector:
    run: webserver
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: webserver-hpa
  namespace: hpa-example
  labels:
    app.kubernetes.io/name: webserver
    app.kubernetes.io/instance: webserver
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webserver-deployment
  minReplicas: 1
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 20
---
